# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_queue', '0002_remove_call_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='personid',
            field=models.TextField(),
        ),
    ]
