# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_queue', '0003_auto_20170802_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 17, 9, 26, 868862)),
            preserve_default=False,
        ),
    ]
